2018-05-28 19:44:07,657 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-28 19:44:34,010 ERROR: Exception on /edit_profile [GET] [in /Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/routes.py", line 93, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/forms.py", line 38, in __init__
    super(EditProfileForm, self).__init_(*args, **kwargs)
AttributeError: 'super' object has no attribute '_EditProfileForm__init_'
2018-05-28 19:44:39,333 ERROR: Exception on /edit_profile [GET] [in /Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/routes.py", line 93, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/forms.py", line 38, in __init__
    super(EditProfileForm, self).__init_(*args, **kwargs)
AttributeError: 'super' object has no attribute '_EditProfileForm__init_'
2018-05-28 19:44:43,874 ERROR: Exception on /edit_profile [GET] [in /Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/routes.py", line 93, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/forms.py", line 38, in __init__
    super(EditProfileForm, self).__init_(*args, **kwargs)
AttributeError: 'super' object has no attribute '_EditProfileForm__init_'
2018-05-28 19:44:53,540 ERROR: Exception on /edit_profile [GET] [in /Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/routes.py", line 93, in edit_profile
    form = EditProfileForm(current_user.username)
  File "/Users/danielobembe/Projects/microblog/venv/lib/python3.6/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/danielobembe/Projects/microblog/app/forms.py", line 38, in __init__
    super(EditProfileForm, self).__init_(*args, **kwargs)
AttributeError: 'super' object has no attribute '_EditProfileForm__init_'
2018-05-28 19:47:11,634 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 17:30:41,094 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 17:31:06,823 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 18:43:48,779 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 18:44:11,122 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 18:45:30,418 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 18:45:50,658 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 18:46:30,615 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 19:35:49,714 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-29 19:39:29,557 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-30 17:30:34,619 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-30 17:58:11,078 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-30 18:19:27,802 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-30 18:21:09,539 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
2018-05-31 19:43:44,696 INFO: Microblog startup [in /Users/danielobembe/Projects/microblog/app/__init__.py:50]
